result_path: "./result"
pretrained_model_name_or_path: "naver-clova-ix/donut-base" # loading a pre-trained model (from moldehub or path)
dataset_name_or_paths: ["../vista-dat/Donut_format"] # loading datasets (from moldehub or path)
task_name: "receipt_parsing" # task for Japanese receipt parsing
sort_json_key: False # custom dataset for Japanese receipts
train_batch_sizes: [8]
val_batch_sizes: [8]
input_size: [2560, 1920] # when the input resolution differs from the pre-training setting, some weights will be newly initialized (but the model training would be okay)
max_length: 768
align_long_axis: False
num_nodes: 1
seed: 2022
lr: 3e-5
warmup_steps: 5 # adjusted for increased batch size and gradient accumulation
num_training_samples_per_epoch: 702 # adjusted for actual dataset size (~50 train images)
max_epochs: 500 # increased to allow more training
max_steps: -1
num_workers: 16
precision: "16-mixed"
val_check_interval: 1.0
check_val_every_n_epoch: 3
gradient_clip_val: 1.0
gradient_accumulation_steps: 2
verbose: True